### PR TITLE
Update community-tools.md

### PR DESCRIPTION
**Pull request by edizbaha**

### CODE REVIEW

**Comment by Vukkyy** [comment]
Aren't most of these tools "API tools"?

**Comment by edizbaha** [comment]
> Aren't most of these tools "API tools"?

Actually yes, but my bot has several API features. I didn't want it to be under one feature.

**Comment by Vukkyy** [comment]
Aren't most of these tools "API tools"?

**Comment by Vukkyy** [comment]
Oh, sorry, I forgot there were multiple sections.

**Review by newbold — APPROVED** [review]

**Pull request merged**
