### PR TITLE
add Vukkybox

### PR DESCRIPTION
**Pull request by Vukkyy**
i doubt you'll accept this but... pfft why not lol

### CODE REVIEW

**Comment by vtheskeleton** [comment]
we will reward you with 5000 Vukkybux upon merging

**Comment by Vukkyy** [comment]
neatnik doesn't even have a vukkybox account stop bribing him with like $5 of useless currency

**Comment by vtheskeleton** [comment]
its never too late

**Comment by lakerjv** [comment]
rip lmao

**Pull request closed without merging**
