### PR TITLE
Add GitHub "Sponsor" button

### PR DESCRIPTION
**Pull request by Vukkyy**
_edit: thank you all for your insightful comments_

This PR adds the required file for the GitHub sponsor button, which shows people where they can sponsor the repository. In this case, that's the OMG.LOL sign up link! :^)

The button looks like this:
sponsor
sponsorpanel

Make sure that you have "Sponsorships" enabled in the settings of this repository. This allows the button to be displayed, and should not be confused with GitHub Sponsors, which allows you to donate money to organizations or users. Confusing!

**When you have merged the PR**, [go here](https://github.com/neatnik/omg.lol/settings) and enable the "Sponsorships" setting. The button should then appear! Fun.
image

### CODE REVIEW

**Comment by byemc** [comment]
imagine adding a button

**Comment by lxjv** [comment]
imagine buttons

**Comment by Mar0xy** [comment]
use your mind

**Review by byemc — CHANGES_REQUESTED** [review]
me telepathically sending adam $5 a year

**Review by byemc — CHANGES_REQUESTED** [review]
add telepathic pay button

**Comment by newbold** [comment]
❤️

**Review by newbold — APPROVED** [review]

**Comment by byemc** [comment]
> use your mind

agreed

**Pull request merged**
