### PR TITLE
Add spacehey icon

### PR DESCRIPTION
**Pull request by AnTheMaker**
Hi there!
I'm building [SpaceHey](https://spacehey.com), a retro social network! I'd love to have an icon for SpaceHey on omg.lol profiles!
screenshot

I added an entry for spacehey in the Markdown file, but couldn't find a way to actually add the icon file (svg?) to the repo as `omg-icon spacehey` - how does this work?

Thank you!

Edit: The SpaceHey Icon (in PNG or SVG) format can be downloaded here: https://spacehey.com/brand

### CODE REVIEW

**Comment by newbold** [comment]
Sorry about the state of the repo! I need to clean that up and make things more consistent. The icon setup is a little sensitive, too, and needs the SVGs to have a single path (though I can try to convert your icon into that format for you, no problem). One quick question — to improve readability of the "hey" text, would you be OK with a modified icon that just features the bubble with that text? Totally up to you, just let me know!

**Comment by AnTheMaker** [comment]
Sure, just the speech bubble with the text would be okay too in this scenario! Consider this my permission :)
Would be awesome if you could convert it!
Thank you so much!! :D

**Comment by newbold** [comment]
OK, done! Here's how it looks:

Screen Shot 2021-09-06 at 12 31 44 PM

Gives a good sense of just how micro scoping the "hey" would have been in the full version. I think it looks great like this though! But I'm glad to make any further adjustments if you're interested, no problem at all.

**Comment by AnTheMaker** [comment]
That looks awesome!! Thank you so much!

**Comment by AnTheMaker** [comment]
It's fixed! Thank you!!

**Pull request merged**
