### PR TITLE
fix: Add hr linebreak color to monokai theme

### PR DESCRIPTION
**Pull request by dcchambers**
This makes the `hr` line break the same color as the text. Before this style was not set and it was very hard to see any `hr` linebreaks with this theme.

Before:

The linebreak color was set to `#333333` by default, making it basically impossible to see.

image

After:

image

### CODE REVIEW

**Comment by dcchambers** [comment]
Changes from `feat` to `fix` because this was an oversight in the original css and should have been in there when I originally submitted the theme 😬

**Comment by dcchambers** [comment]
@newbold just a gentle bump on this. Thanks!

**Review by newbold — APPROVED** [review]

**Comment by newbold** [comment]
Huge apologies for the delay on this!

**Comment by dcchambers** [comment]
@newbold it's all good 🎉 thanks! 🍻

**Pull request merged**
