### PR TITLE
Add Mastodon inspired theme

### PR DESCRIPTION
**Pull request by jordan-warne**
I created a theme inspired by Mastodon's blurple colour scheme. Here's a preview:

Screenshot 2024-03-16 at 6 00 06 pm

### CODE REVIEW

**Comment by andypiper** [comment]
Love it (and want to use it!)

**Comment by andypiper** [comment]
I added it into my custom CSS for my page https://andypiper.omg.lol/ and also added a tweak to use Manrope from Google Fonts instead of Roboto (which I think is what Mastodon uses, FWIW). Love it. Hope this can be added for everyone 🙂

**Comment by jordan-warne** [comment]
Glad you like it! I changed the font to the Google Manrope font

**Review by newbold — APPROVED** [review]

**Comment by newbold** [comment]
Sorry for the delay in getting this added! All set now. 👍

**Comment by andypiper** [comment]
Cool, switched over to the theme properly now. Thanks for adding.

**Pull request merged**
