### PR TITLE
codeblock syntax highlight

### PR DESCRIPTION
**Pull request by weiw11**
Defines code block code to enable syntax highlighting.

### CODE REVIEW

**Comment by newbold** [comment]
Thanks for suggesting this! I don’t think my Markdown interpreter handles syntax highlighting, so I’m 99% sure that if I merge this we’ll see `json` and `html` and stuff like that on the Info Center page instead of nice highlighting. Let me look into options and see if we can find a way to make it work. Thanks again!

**Comment by drudge** [comment]
I'm using these language hints on my blog and your renderer does use them to apply `language-${slug}` classes to the codeblocks. These hints are not rendered on the page. This was of great use to me when adding syntax highlighting to my blog:

Example: https://blog.penree.com/2023/01/new-tidbyt-app-mastodon-follows

**Comment by weiw11** [comment]
> Example: https://blog.penree.com/2023/01/new-tidbyt-app-mastodon-follows

Wow your blog looks amazing!

**Review by newbold — APPROVED** [review]

**Comment by newbold** [comment]
Sorry for the delay in taking care of this! Just upgraded our Markdown engine to support these code blocks, and I’ll have highlight.js running shortly. Really appreciate the suggestion!

**Pull request merged**
