### PR TITLE
Apostrophe

### PR DESCRIPTION
**Pull request by Vukkyy**
I will become back my money. I cannot believe your skilled moderator would make such a mistake.

/j

### CODE REVIEW

**Comment by lxjv** [comment]
A: whoops
b: skilled and Me should not be in the same sentence

**Comment by Vukkyy** [comment]
Also, I wonder if it would make sense for it to be a subsection of "connecting" instead of being all the way at the bottom

or is that too many subsections

**Comment by lxjv** [comment]
i put it at the bottom as both me and adam dont like discord that much ( i am less averse but eh )

**Comment by lxjv** [comment]
i will talk to adam about it XD

**Comment by lxjv** [comment]
finally merging this!

**Pull request merged**
